esphomeyaml:
  name: spark01
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password


light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 20
    rgb_order: GRB
    name: "Spark 01"
    effects:
      - fastled_random_twinkle:
      - fastled_twinkle:
      - fastled_fireworks:
      - fastled_rainbow:
      - fastled_color_wipe: 
      - fastled_scan:
      - fastled_flicker: 
