esphomeyaml:
  name: spark02
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password


binary_sensor:
  - platform: gpio
    name: Button 01
    pin:
     number: D3
     mode: INPUT_PULLUP
     inverted: True
    filters:
      - delayed_on: 10ms


switch:
  - platform: gpio
    pin: D1
    name: "Relay 01"
